[package]
name = "stlink"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.7"
nanoid = "0.4"
serde = "1"
shuttle-axum = "0.47"
redis = { version = "0.23.0", features = ["tls-native-tls"] }
shuttle-runtime = "0.47"
